// Generated by CoffeeScript 1.4.0

Workspace.controller('ProjectDetailsCtrl', [
  '$rootScope', '$scope', '$stateParams', 'collectionAssetData', function($rootScope, $scope, $stateParams, collectionAssetData) {
    $rootScope.$broadcast('navigatedTo', 'Projects');
    $scope.currentAnnotation = _.find(collectionAssetData.assetData, function(item) {
      return item.project.id === parseInt($stateParams.projectID);
    });
    return em.unit;
  }
]);
