// Generated by CoffeeScript 1.4.0

Workspace.controller('ProjectDetailsCtrl', [
  '$scope', '$stateParams', 'collectionAssetData', function($scope, $stateParams, collectionAssetData) {
    $scope.currentAnnotation = _.find(collectionAssetData.assetData, function(item) {
      return item.project.id === parseInt($stateParams.projectID);
    });
    return em.unit;
  }
]);
