// Generated by CoffeeScript 1.4.0

Workspace.factory('annotationSocket', [
  '$rootScope', function($rootScope) {
    var base_destination, connection, final_destination;
    connection = null;
    if (window.WebSocket) {
      base_destination = "ws://localhost:8080/entermedia/services/websocket/echoProgrammatic";
      final_destination = "" + base_destination + "?catalogid=" + catalogid + "&collectionid=" + collectionid;
      connection = new WebSocket(final_destination);
      connection.onopen = function(e) {
        console.log('Opened a connection!');
        return em.unit;
      };
      connection.onclose = function(e) {
        console.log('Closed a connection!');
        return em.unit;
      };
      connection.onerror = function(e) {
        console.log('Connection error!');
        console.log(e);
        return em.unit;
      };
      connection.onmessage = function(e) {
        var data;
        console.log('Received message');
        data = JSON.parse(e.data);
        return $rootScope.$broadcast(data.command, data);
      };
    }
    return connection;
  }
]);
