// Generated by CoffeeScript 1.4.0

Workspace.factory('collectionAssetData', function() {
  var assetSpec, image, result, _i, _len, _ref;
  result = {};
  $.ajax({
    type: "GET",
    url: "" + apphome + "/components/annotations/json/viewassets.json?id=" + collectionid,
    async: false,
    error: function(data, status, err) {
      console.log('from error:', data);
      return em.unit;
    },
    success: function(data) {
      console.log('from success:', data);
      result.imageData = data;
      return em.unit;
    },
    failure: function(errMsg) {
      alert(errMsg);
      return em.unit;
    }
  });
  /*
  	# project:
  	# 		id: 1
  	# 		name: "Bad Project"
  	# 	annotation:
  	# 		id: 101
  	# 		name: "Stupid art"
  	# 		description: "This is my fifth child's bad art"
  	# 		status: 'Done'
  	# 		hasRecentActivity: true
  	# 		createTime: '05/04/2014 14:33:56'
  	# 		lastUpdateTime: '05/06/2014 06:30:23'
  	# 		owner: 'Bob Dole'
  	# 		path: 'img/ForMom.jpg'
  */

  result.assetData = [];
  result.thumbs = (function() {
    var _i, _len, _ref, _results;
    _ref = result.imageData;
    _results = [];
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      image = _ref[_i];
      _results.push({
        id: image.id,
        sourcepath: image.thumb
      });
    }
    return _results;
  })();
  result.images = (function() {
    var _i, _len, _ref, _results;
    _ref = result.imageData;
    _results = [];
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      image = _ref[_i];
      _results.push({
        id: image.id,
        sourcepath: image.sourcepath
      });
    }
    return _results;
  })();
  result.assets = (function() {
    var _i, _len, _ref, _results;
    _ref = result.imageData;
    _results = [];
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      image = _ref[_i];
      _results.push(image.id);
    }
    return _results;
  })();
  result.collectionid = collectionid;
  _ref = result.imageData;
  for (_i = 0, _len = _ref.length; _i < _len; _i++) {
    assetSpec = _ref[_i];
    result.assetData.push({
      project: {
        id: 1,
        name: "None"
      },
      annotation: {
        id: assetSpec.id,
        name: "None",
        description: "None",
        status: 'None',
        hasRecentActivity: 'none',
        createTime: '4 B.C.',
        lastUpdateTime: '2000 A.D.',
        owner: 'Enrico Fermi',
        sourcepath: assetSpec.sourcepath,
        assetspec: assetSpec
      }
    });
  }
  result.getSrc = function(id, size) {
    var found, where;
    switch (size) {
      case 'thumb' || 'thumbs':
        where = result.thumbs;
        break;
      default:
        where = result.images;
    }
    found = _.findWhere(where, {
      id: id
    });
    return found;
  };
  return result;
});
